version: '3.8'

services:
  flask:
    build:
      context: todo
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      FLASK_SECRET_KEY: secret
      MONGODB_DATABASE: testdb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    volumes:
      - '.:/opt'
    depends_on:
      - mongodb
    networks:
      - playground

  mongodb:
    image: mongo:4-bionic
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - playground

volumes:
  mongodb:

networks:
  playground:
    driver: bridge
